name: DeployFront

on:
  push:
    branches:
      - fe-dev  # fe-dev 브랜치에 push할 때만 이벤트를 트리거합니다.

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.14.0'  # 프로젝트에서 사용하는 Node.js 버전으로 변경

    - name: Install dependencies
      working-directory: FE/airdnb_fe
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    - name: Build
      working-directory: FE/airdnb_fe
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2  # AWS 리전을 프로젝트에 맞게 변경

    - name: Deploy to S3
      run: aws s3 sync FE/airdnb_fe/dist/ s3://${{ secrets.S3_BUCKET }} --delete
